irq_pipeline: fix compile issues for irq_active_on_this_cpu()
The irq_active_on_this_cpu() is defined and surrounded with
CONFIG_IRQ_PIPELINE macro. However, the caller doesn't use
it with CONFIG_IRQ_PIPELINE which causes a compile issue when
it is built in "make ARCH=x86_64 allnoconfig" case. The macro
is added to the calling place to fix the issue.

Build error logs:

kernel/irq/chip.c: In function 'irq_may_run':
kernel/irq/chip.c:731:21: error: implicit declaration of function
'irq_active_on_this_cpu' [-Werror=implicit-function-declaration]
  731 |                 if (irq_active_on_this_cpu(desc))
      |                     ^~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Wang, Yuan1 <yuan1.wang@intel.com>